// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: event.proto

package azdext

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents different types of messages sent over the stream
type EventMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MessageType:
	//
	//	*EventMessage_SubscribeProjectEvent
	//	*EventMessage_InvokeProjectHandler
	//	*EventMessage_ProjectHandlerStatus
	//	*EventMessage_SubscribeServiceEvent
	//	*EventMessage_InvokeServiceHandler
	//	*EventMessage_ServiceHandlerStatus
	//	*EventMessage_SubscribeLayerEvent
	//	*EventMessage_InvokeLayerHandler
	//	*EventMessage_LayerHandlerStatus
	MessageType   isEventMessage_MessageType `protobuf_oneof:"message_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMessage) Reset() {
	*x = EventMessage{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMessage) ProtoMessage() {}

func (x *EventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMessage.ProtoReflect.Descriptor instead.
func (*EventMessage) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *EventMessage) GetMessageType() isEventMessage_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *EventMessage) GetSubscribeProjectEvent() *SubscribeProjectEvent {
	if x != nil {
		if x, ok := x.MessageType.(*EventMessage_SubscribeProjectEvent); ok {
			return x.SubscribeProjectEvent
		}
	}
	return nil
}

func (x *EventMessage) GetInvokeProjectHandler() *InvokeProjectHandler {
	if x != nil {
		if x, ok := x.MessageType.(*EventMessage_InvokeProjectHandler); ok {
			return x.InvokeProjectHandler
		}
	}
	return nil
}

func (x *EventMessage) GetProjectHandlerStatus() *ProjectHandlerStatus {
	if x != nil {
		if x, ok := x.MessageType.(*EventMessage_ProjectHandlerStatus); ok {
			return x.ProjectHandlerStatus
		}
	}
	return nil
}

func (x *EventMessage) GetSubscribeServiceEvent() *SubscribeServiceEvent {
	if x != nil {
		if x, ok := x.MessageType.(*EventMessage_SubscribeServiceEvent); ok {
			return x.SubscribeServiceEvent
		}
	}
	return nil
}

func (x *EventMessage) GetInvokeServiceHandler() *InvokeServiceHandler {
	if x != nil {
		if x, ok := x.MessageType.(*EventMessage_InvokeServiceHandler); ok {
			return x.InvokeServiceHandler
		}
	}
	return nil
}

func (x *EventMessage) GetServiceHandlerStatus() *ServiceHandlerStatus {
	if x != nil {
		if x, ok := x.MessageType.(*EventMessage_ServiceHandlerStatus); ok {
			return x.ServiceHandlerStatus
		}
	}
	return nil
}

func (x *EventMessage) GetSubscribeLayerEvent() *SubscribeLayerEvent {
	if x != nil {
		if x, ok := x.MessageType.(*EventMessage_SubscribeLayerEvent); ok {
			return x.SubscribeLayerEvent
		}
	}
	return nil
}

func (x *EventMessage) GetInvokeLayerHandler() *InvokeLayerHandler {
	if x != nil {
		if x, ok := x.MessageType.(*EventMessage_InvokeLayerHandler); ok {
			return x.InvokeLayerHandler
		}
	}
	return nil
}

func (x *EventMessage) GetLayerHandlerStatus() *LayerHandlerStatus {
	if x != nil {
		if x, ok := x.MessageType.(*EventMessage_LayerHandlerStatus); ok {
			return x.LayerHandlerStatus
		}
	}
	return nil
}

type isEventMessage_MessageType interface {
	isEventMessage_MessageType()
}

type EventMessage_SubscribeProjectEvent struct {
	SubscribeProjectEvent *SubscribeProjectEvent `protobuf:"bytes,1,opt,name=subscribe_project_event,json=subscribeProjectEvent,proto3,oneof"`
}

type EventMessage_InvokeProjectHandler struct {
	InvokeProjectHandler *InvokeProjectHandler `protobuf:"bytes,2,opt,name=invoke_project_handler,json=invokeProjectHandler,proto3,oneof"`
}

type EventMessage_ProjectHandlerStatus struct {
	ProjectHandlerStatus *ProjectHandlerStatus `protobuf:"bytes,3,opt,name=project_handler_status,json=projectHandlerStatus,proto3,oneof"`
}

type EventMessage_SubscribeServiceEvent struct {
	SubscribeServiceEvent *SubscribeServiceEvent `protobuf:"bytes,4,opt,name=subscribe_service_event,json=subscribeServiceEvent,proto3,oneof"`
}

type EventMessage_InvokeServiceHandler struct {
	InvokeServiceHandler *InvokeServiceHandler `protobuf:"bytes,5,opt,name=invoke_service_handler,json=invokeServiceHandler,proto3,oneof"`
}

type EventMessage_ServiceHandlerStatus struct {
	ServiceHandlerStatus *ServiceHandlerStatus `protobuf:"bytes,6,opt,name=service_handler_status,json=serviceHandlerStatus,proto3,oneof"`
}

type EventMessage_SubscribeLayerEvent struct {
	SubscribeLayerEvent *SubscribeLayerEvent `protobuf:"bytes,8,opt,name=subscribe_layer_event,json=subscribeLayerEvent,proto3,oneof"`
}

type EventMessage_InvokeLayerHandler struct {
	InvokeLayerHandler *InvokeLayerHandler `protobuf:"bytes,9,opt,name=invoke_layer_handler,json=invokeLayerHandler,proto3,oneof"`
}

type EventMessage_LayerHandlerStatus struct {
	LayerHandlerStatus *LayerHandlerStatus `protobuf:"bytes,10,opt,name=layer_handler_status,json=layerHandlerStatus,proto3,oneof"`
}

func (*EventMessage_SubscribeProjectEvent) isEventMessage_MessageType() {}

func (*EventMessage_InvokeProjectHandler) isEventMessage_MessageType() {}

func (*EventMessage_ProjectHandlerStatus) isEventMessage_MessageType() {}

func (*EventMessage_SubscribeServiceEvent) isEventMessage_MessageType() {}

func (*EventMessage_InvokeServiceHandler) isEventMessage_MessageType() {}

func (*EventMessage_ServiceHandlerStatus) isEventMessage_MessageType() {}

func (*EventMessage_SubscribeLayerEvent) isEventMessage_MessageType() {}

func (*EventMessage_InvokeLayerHandler) isEventMessage_MessageType() {}

func (*EventMessage_LayerHandlerStatus) isEventMessage_MessageType() {}

// Client subscribes to project-related events
type SubscribeProjectEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of event names to subscribe to.
	EventNames    []string `protobuf:"bytes,1,rep,name=event_names,json=eventNames,proto3" json:"event_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeProjectEvent) Reset() {
	*x = SubscribeProjectEvent{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeProjectEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeProjectEvent) ProtoMessage() {}

func (x *SubscribeProjectEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeProjectEvent.ProtoReflect.Descriptor instead.
func (*SubscribeProjectEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeProjectEvent) GetEventNames() []string {
	if x != nil {
		return x.EventNames
	}
	return nil
}

// Client subscribes to service-related events
type SubscribeServiceEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of event names to subscribe to.
	EventNames    []string `protobuf:"bytes,1,rep,name=event_names,json=eventNames,proto3" json:"event_names,omitempty"`
	Language      string   `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Host          string   `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeServiceEvent) Reset() {
	*x = SubscribeServiceEvent{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeServiceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeServiceEvent) ProtoMessage() {}

func (x *SubscribeServiceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeServiceEvent.ProtoReflect.Descriptor instead.
func (*SubscribeServiceEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeServiceEvent) GetEventNames() []string {
	if x != nil {
		return x.EventNames
	}
	return nil
}

func (x *SubscribeServiceEvent) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SubscribeServiceEvent) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

// Client subscribes to layer-related events.
type SubscribeLayerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventNames    []string               `protobuf:"bytes,1,rep,name=event_names,json=eventNames,proto3" json:"event_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeLayerEvent) Reset() {
	*x = SubscribeLayerEvent{}
	mi := &file_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeLayerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeLayerEvent) ProtoMessage() {}

func (x *SubscribeLayerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeLayerEvent.ProtoReflect.Descriptor instead.
func (*SubscribeLayerEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeLayerEvent) GetEventNames() []string {
	if x != nil {
		return x.EventNames
	}
	return nil
}

// ExecutionScope describes the layers and services selected for one command.
type ExecutionScope struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TargetLayers        []string               `protobuf:"bytes,1,rep,name=target_layers,json=targetLayers,proto3" json:"target_layers,omitempty"`
	IncludedLayers      []string               `protobuf:"bytes,2,rep,name=included_layers,json=includedLayers,proto3" json:"included_layers,omitempty"`
	ServiceNames        []string               `protobuf:"bytes,3,rep,name=service_names,json=serviceNames,proto3" json:"service_names,omitempty"`
	IncludeDependencies bool                   `protobuf:"varint,4,opt,name=include_dependencies,json=includeDependencies,proto3" json:"include_dependencies,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExecutionScope) Reset() {
	*x = ExecutionScope{}
	mi := &file_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionScope) ProtoMessage() {}

func (x *ExecutionScope) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionScope.ProtoReflect.Descriptor instead.
func (*ExecutionScope) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{4}
}

func (x *ExecutionScope) GetTargetLayers() []string {
	if x != nil {
		return x.TargetLayers
	}
	return nil
}

func (x *ExecutionScope) GetIncludedLayers() []string {
	if x != nil {
		return x.IncludedLayers
	}
	return nil
}

func (x *ExecutionScope) GetServiceNames() []string {
	if x != nil {
		return x.ServiceNames
	}
	return nil
}

func (x *ExecutionScope) GetIncludeDependencies() bool {
	if x != nil {
		return x.IncludeDependencies
	}
	return false
}

// Server invokes the project event handler
type InvokeProjectHandler struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the event being invoked.
	EventName string `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	// Current project configuration.
	Project       *ProjectConfig  `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Scope         *ExecutionScope `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeProjectHandler) Reset() {
	*x = InvokeProjectHandler{}
	mi := &file_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeProjectHandler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeProjectHandler) ProtoMessage() {}

func (x *InvokeProjectHandler) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeProjectHandler.ProtoReflect.Descriptor instead.
func (*InvokeProjectHandler) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{5}
}

func (x *InvokeProjectHandler) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *InvokeProjectHandler) GetProject() *ProjectConfig {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *InvokeProjectHandler) GetScope() *ExecutionScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

// Server invokes a layer event handler.
type InvokeLayerHandler struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventName     string                 `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	Project       *ProjectConfig         `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Layer         *Layer                 `protobuf:"bytes,3,opt,name=layer,proto3" json:"layer,omitempty"`
	Scope         *ExecutionScope        `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeLayerHandler) Reset() {
	*x = InvokeLayerHandler{}
	mi := &file_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeLayerHandler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeLayerHandler) ProtoMessage() {}

func (x *InvokeLayerHandler) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeLayerHandler.ProtoReflect.Descriptor instead.
func (*InvokeLayerHandler) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{6}
}

func (x *InvokeLayerHandler) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *InvokeLayerHandler) GetProject() *ProjectConfig {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *InvokeLayerHandler) GetLayer() *Layer {
	if x != nil {
		return x.Layer
	}
	return nil
}

func (x *InvokeLayerHandler) GetScope() *ExecutionScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

// Server invokes the service event handler
type InvokeServiceHandler struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the event being invoked.
	EventName string `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	// Current project configuration.
	Project *ProjectConfig `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	// Specific service configuration.
	Service *ServiceConfig `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	// Service context with artifacts from all lifecycle phases.
	ServiceContext *ServiceContext `protobuf:"bytes,4,opt,name=service_context,json=serviceContext,proto3" json:"service_context,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InvokeServiceHandler) Reset() {
	*x = InvokeServiceHandler{}
	mi := &file_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeServiceHandler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeServiceHandler) ProtoMessage() {}

func (x *InvokeServiceHandler) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeServiceHandler.ProtoReflect.Descriptor instead.
func (*InvokeServiceHandler) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{7}
}

func (x *InvokeServiceHandler) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *InvokeServiceHandler) GetProject() *ProjectConfig {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *InvokeServiceHandler) GetService() *ServiceConfig {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *InvokeServiceHandler) GetServiceContext() *ServiceContext {
	if x != nil {
		return x.ServiceContext
	}
	return nil
}

// Client sends status updates for project events
type ProjectHandlerStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the event this status update is for.
	EventName string `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	// Status such as "running", "completed", "failed", etc.
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Optional message providing further details.
	// For backward compatibility with older hosts, populate this even when error is set.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Optional structured error details (set when status is "failed").
	Error         *ExtensionError `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectHandlerStatus) Reset() {
	*x = ProjectHandlerStatus{}
	mi := &file_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectHandlerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectHandlerStatus) ProtoMessage() {}

func (x *ProjectHandlerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectHandlerStatus.ProtoReflect.Descriptor instead.
func (*ProjectHandlerStatus) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{8}
}

func (x *ProjectHandlerStatus) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *ProjectHandlerStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProjectHandlerStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProjectHandlerStatus) GetError() *ExtensionError {
	if x != nil {
		return x.Error
	}
	return nil
}

// Client sends status updates for service events
type ServiceHandlerStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the event this status update is for.
	EventName string `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	// Name of the service related to the update.
	ServiceName string `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Status such as "running", "completed", "failed", etc.
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// Optional message providing further details.
	// For backward compatibility with older hosts, populate this even when error is set.
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Optional structured error details (set when status is "failed").
	Error         *ExtensionError `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceHandlerStatus) Reset() {
	*x = ServiceHandlerStatus{}
	mi := &file_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceHandlerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceHandlerStatus) ProtoMessage() {}

func (x *ServiceHandlerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceHandlerStatus.ProtoReflect.Descriptor instead.
func (*ServiceHandlerStatus) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{9}
}

func (x *ServiceHandlerStatus) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *ServiceHandlerStatus) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceHandlerStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceHandlerStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServiceHandlerStatus) GetError() *ExtensionError {
	if x != nil {
		return x.Error
	}
	return nil
}

// Client sends status updates for layer events.
type LayerHandlerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventName     string                 `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	LayerName     string                 `protobuf:"bytes,2,opt,name=layer_name,json=layerName,proto3" json:"layer_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Error         *ExtensionError        `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayerHandlerStatus) Reset() {
	*x = LayerHandlerStatus{}
	mi := &file_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayerHandlerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerHandlerStatus) ProtoMessage() {}

func (x *LayerHandlerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerHandlerStatus.ProtoReflect.Descriptor instead.
func (*LayerHandlerStatus) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{10}
}

func (x *LayerHandlerStatus) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *LayerHandlerStatus) GetLayerName() string {
	if x != nil {
		return x.LayerName
	}
	return ""
}

func (x *LayerHandlerStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LayerHandlerStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LayerHandlerStatus) GetError() *ExtensionError {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\x06azdext\x1a\fmodels.proto\x1a\ferrors.proto\x1a\rproject.proto\"\x9b\x06\n" +
	"\fEventMessage\x12W\n" +
	"\x17subscribe_project_event\x18\x01 \x01(\v2\x1d.azdext.SubscribeProjectEventH\x00R\x15subscribeProjectEvent\x12T\n" +
	"\x16invoke_project_handler\x18\x02 \x01(\v2\x1c.azdext.InvokeProjectHandlerH\x00R\x14invokeProjectHandler\x12T\n" +
	"\x16project_handler_status\x18\x03 \x01(\v2\x1c.azdext.ProjectHandlerStatusH\x00R\x14projectHandlerStatus\x12W\n" +
	"\x17subscribe_service_event\x18\x04 \x01(\v2\x1d.azdext.SubscribeServiceEventH\x00R\x15subscribeServiceEvent\x12T\n" +
	"\x16invoke_service_handler\x18\x05 \x01(\v2\x1c.azdext.InvokeServiceHandlerH\x00R\x14invokeServiceHandler\x12T\n" +
	"\x16service_handler_status\x18\x06 \x01(\v2\x1c.azdext.ServiceHandlerStatusH\x00R\x14serviceHandlerStatus\x12Q\n" +
	"\x15subscribe_layer_event\x18\b \x01(\v2\x1b.azdext.SubscribeLayerEventH\x00R\x13subscribeLayerEvent\x12N\n" +
	"\x14invoke_layer_handler\x18\t \x01(\v2\x1a.azdext.InvokeLayerHandlerH\x00R\x12invokeLayerHandler\x12N\n" +
	"\x14layer_handler_status\x18\n" +
	" \x01(\v2\x1a.azdext.LayerHandlerStatusH\x00R\x12layerHandlerStatusB\x0e\n" +
	"\fmessage_type\"8\n" +
	"\x15SubscribeProjectEvent\x12\x1f\n" +
	"\vevent_names\x18\x01 \x03(\tR\n" +
	"eventNames\"h\n" +
	"\x15SubscribeServiceEvent\x12\x1f\n" +
	"\vevent_names\x18\x01 \x03(\tR\n" +
	"eventNames\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\"6\n" +
	"\x13SubscribeLayerEvent\x12\x1f\n" +
	"\vevent_names\x18\x01 \x03(\tR\n" +
	"eventNames\"\xb6\x01\n" +
	"\x0eExecutionScope\x12#\n" +
	"\rtarget_layers\x18\x01 \x03(\tR\ftargetLayers\x12'\n" +
	"\x0fincluded_layers\x18\x02 \x03(\tR\x0eincludedLayers\x12#\n" +
	"\rservice_names\x18\x03 \x03(\tR\fserviceNames\x121\n" +
	"\x14include_dependencies\x18\x04 \x01(\bR\x13includeDependencies\"\x94\x01\n" +
	"\x14InvokeProjectHandler\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12/\n" +
	"\aproject\x18\x02 \x01(\v2\x15.azdext.ProjectConfigR\aproject\x12,\n" +
	"\x05scope\x18\x03 \x01(\v2\x16.azdext.ExecutionScopeR\x05scope\"\xb7\x01\n" +
	"\x12InvokeLayerHandler\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12/\n" +
	"\aproject\x18\x02 \x01(\v2\x15.azdext.ProjectConfigR\aproject\x12#\n" +
	"\x05layer\x18\x03 \x01(\v2\r.azdext.LayerR\x05layer\x12,\n" +
	"\x05scope\x18\x04 \x01(\v2\x16.azdext.ExecutionScopeR\x05scope\"\xd8\x01\n" +
	"\x14InvokeServiceHandler\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12/\n" +
	"\aproject\x18\x02 \x01(\v2\x15.azdext.ProjectConfigR\aproject\x12/\n" +
	"\aservice\x18\x03 \x01(\v2\x15.azdext.ServiceConfigR\aservice\x12?\n" +
	"\x0fservice_context\x18\x04 \x01(\v2\x16.azdext.ServiceContextR\x0eserviceContext\"\x95\x01\n" +
	"\x14ProjectHandlerStatus\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12,\n" +
	"\x05error\x18\x04 \x01(\v2\x16.azdext.ExtensionErrorR\x05error\"\xb8\x01\n" +
	"\x14ServiceHandlerStatus\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12,\n" +
	"\x05error\x18\x05 \x01(\v2\x16.azdext.ExtensionErrorR\x05error\"\xb2\x01\n" +
	"\x12LayerHandlerStatus\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12\x1d\n" +
	"\n" +
	"layer_name\x18\x02 \x01(\tR\tlayerName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12,\n" +
	"\x05error\x18\x05 \x01(\v2\x16.azdext.ExtensionErrorR\x05error2M\n" +
	"\fEventService\x12=\n" +
	"\vEventStream\x12\x14.azdext.EventMessage\x1a\x14.azdext.EventMessage(\x010\x01B/Z-github.com/azure/azure-dev/cli/azd/pkg/azdextb\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_event_proto_goTypes = []any{
	(*EventMessage)(nil),          // 0: azdext.EventMessage
	(*SubscribeProjectEvent)(nil), // 1: azdext.SubscribeProjectEvent
	(*SubscribeServiceEvent)(nil), // 2: azdext.SubscribeServiceEvent
	(*SubscribeLayerEvent)(nil),   // 3: azdext.SubscribeLayerEvent
	(*ExecutionScope)(nil),        // 4: azdext.ExecutionScope
	(*InvokeProjectHandler)(nil),  // 5: azdext.InvokeProjectHandler
	(*InvokeLayerHandler)(nil),    // 6: azdext.InvokeLayerHandler
	(*InvokeServiceHandler)(nil),  // 7: azdext.InvokeServiceHandler
	(*ProjectHandlerStatus)(nil),  // 8: azdext.ProjectHandlerStatus
	(*ServiceHandlerStatus)(nil),  // 9: azdext.ServiceHandlerStatus
	(*LayerHandlerStatus)(nil),    // 10: azdext.LayerHandlerStatus
	(*ProjectConfig)(nil),         // 11: azdext.ProjectConfig
	(*Layer)(nil),                 // 12: azdext.Layer
	(*ServiceConfig)(nil),         // 13: azdext.ServiceConfig
	(*ServiceContext)(nil),        // 14: azdext.ServiceContext
	(*ExtensionError)(nil),        // 15: azdext.ExtensionError
}
var file_event_proto_depIdxs = []int32{
	1,  // 0: azdext.EventMessage.subscribe_project_event:type_name -> azdext.SubscribeProjectEvent
	5,  // 1: azdext.EventMessage.invoke_project_handler:type_name -> azdext.InvokeProjectHandler
	8,  // 2: azdext.EventMessage.project_handler_status:type_name -> azdext.ProjectHandlerStatus
	2,  // 3: azdext.EventMessage.subscribe_service_event:type_name -> azdext.SubscribeServiceEvent
	7,  // 4: azdext.EventMessage.invoke_service_handler:type_name -> azdext.InvokeServiceHandler
	9,  // 5: azdext.EventMessage.service_handler_status:type_name -> azdext.ServiceHandlerStatus
	3,  // 6: azdext.EventMessage.subscribe_layer_event:type_name -> azdext.SubscribeLayerEvent
	6,  // 7: azdext.EventMessage.invoke_layer_handler:type_name -> azdext.InvokeLayerHandler
	10, // 8: azdext.EventMessage.layer_handler_status:type_name -> azdext.LayerHandlerStatus
	11, // 9: azdext.InvokeProjectHandler.project:type_name -> azdext.ProjectConfig
	4,  // 10: azdext.InvokeProjectHandler.scope:type_name -> azdext.ExecutionScope
	11, // 11: azdext.InvokeLayerHandler.project:type_name -> azdext.ProjectConfig
	12, // 12: azdext.InvokeLayerHandler.layer:type_name -> azdext.Layer
	4,  // 13: azdext.InvokeLayerHandler.scope:type_name -> azdext.ExecutionScope
	11, // 14: azdext.InvokeServiceHandler.project:type_name -> azdext.ProjectConfig
	13, // 15: azdext.InvokeServiceHandler.service:type_name -> azdext.ServiceConfig
	14, // 16: azdext.InvokeServiceHandler.service_context:type_name -> azdext.ServiceContext
	15, // 17: azdext.ProjectHandlerStatus.error:type_name -> azdext.ExtensionError
	15, // 18: azdext.ServiceHandlerStatus.error:type_name -> azdext.ExtensionError
	15, // 19: azdext.LayerHandlerStatus.error:type_name -> azdext.ExtensionError
	0,  // 20: azdext.EventService.EventStream:input_type -> azdext.EventMessage
	0,  // 21: azdext.EventService.EventStream:output_type -> azdext.EventMessage
	21, // [21:22] is the sub-list for method output_type
	20, // [20:21] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	file_models_proto_init()
	file_errors_proto_init()
	file_project_proto_init()
	file_event_proto_msgTypes[0].OneofWrappers = []any{
		(*EventMessage_SubscribeProjectEvent)(nil),
		(*EventMessage_InvokeProjectHandler)(nil),
		(*EventMessage_ProjectHandlerStatus)(nil),
		(*EventMessage_SubscribeServiceEvent)(nil),
		(*EventMessage_InvokeServiceHandler)(nil),
		(*EventMessage_ServiceHandlerStatus)(nil),
		(*EventMessage_SubscribeLayerEvent)(nil),
		(*EventMessage_InvokeLayerHandler)(nil),
		(*EventMessage_LayerHandlerStatus)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
