// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: project.proto

package azdext

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoveLayerMode int32

const (
	RemoveLayerMode_REMOVE_LAYER_MODE_REQUIRE_EMPTY    RemoveLayerMode = 0
	RemoveLayerMode_REMOVE_LAYER_MODE_CASCADE_SERVICES RemoveLayerMode = 1
)

// Enum value maps for RemoveLayerMode.
var (
	RemoveLayerMode_name = map[int32]string{
		0: "REMOVE_LAYER_MODE_REQUIRE_EMPTY",
		1: "REMOVE_LAYER_MODE_CASCADE_SERVICES",
	}
	RemoveLayerMode_value = map[string]int32{
		"REMOVE_LAYER_MODE_REQUIRE_EMPTY":    0,
		"REMOVE_LAYER_MODE_CASCADE_SERVICES": 1,
	}
)

func (x RemoveLayerMode) Enum() *RemoveLayerMode {
	p := new(RemoveLayerMode)
	*p = x
	return p
}

func (x RemoveLayerMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoveLayerMode) Descriptor() protoreflect.EnumDescriptor {
	return file_project_proto_enumTypes[0].Descriptor()
}

func (RemoveLayerMode) Type() protoreflect.EnumType {
	return &file_project_proto_enumTypes[0]
}

func (x RemoveLayerMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoveLayerMode.Descriptor instead.
func (RemoveLayerMode) EnumDescriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{0}
}

// GetProjectResponse message definition
type GetProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *ProjectConfig         `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectResponse) Reset() {
	*x = GetProjectResponse{}
	mi := &file_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectResponse) ProtoMessage() {}

func (x *GetProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectResponse.ProtoReflect.Descriptor instead.
func (*GetProjectResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{0}
}

func (x *GetProjectResponse) GetProject() *ProjectConfig {
	if x != nil {
		return x.Project
	}
	return nil
}

// AddServiceRequest message definition
type AddServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *ServiceConfig         `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddServiceRequest) Reset() {
	*x = AddServiceRequest{}
	mi := &file_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddServiceRequest) ProtoMessage() {}

func (x *AddServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddServiceRequest.ProtoReflect.Descriptor instead.
func (*AddServiceRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{1}
}

func (x *AddServiceRequest) GetService() *ServiceConfig {
	if x != nil {
		return x.Service
	}
	return nil
}

// LayerDefinition is the persisted configuration accepted by layer mutations.
type LayerDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Infra         *InfraOptions          `protobuf:"bytes,2,opt,name=infra,proto3" json:"infra,omitempty"`
	DependsOn     []string               `protobuf:"bytes,3,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	Inputs        map[string]string      `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Outputs       map[string]string      `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayerDefinition) Reset() {
	*x = LayerDefinition{}
	mi := &file_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayerDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerDefinition) ProtoMessage() {}

func (x *LayerDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerDefinition.ProtoReflect.Descriptor instead.
func (*LayerDefinition) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{2}
}

func (x *LayerDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LayerDefinition) GetInfra() *InfraOptions {
	if x != nil {
		return x.Infra
	}
	return nil
}

func (x *LayerDefinition) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *LayerDefinition) GetInputs() map[string]string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *LayerDefinition) GetOutputs() map[string]string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

// Layer is the resolved view of an infrastructure-backed, service-only, or implicit layer.
type Layer struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Name          string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Infra         *InfraOptions             `protobuf:"bytes,2,opt,name=infra,proto3" json:"infra,omitempty"`
	Services      map[string]*ServiceConfig `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DependsOn     []string                  `protobuf:"bytes,4,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	Inputs        map[string]string         `protobuf:"bytes,5,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Outputs       map[string]string         `protobuf:"bytes,6,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Implicit      bool                      `protobuf:"varint,7,opt,name=implicit,proto3" json:"implicit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Layer) Reset() {
	*x = Layer{}
	mi := &file_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Layer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layer) ProtoMessage() {}

func (x *Layer) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layer.ProtoReflect.Descriptor instead.
func (*Layer) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{3}
}

func (x *Layer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Layer) GetInfra() *InfraOptions {
	if x != nil {
		return x.Infra
	}
	return nil
}

func (x *Layer) GetServices() map[string]*ServiceConfig {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Layer) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *Layer) GetInputs() map[string]string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *Layer) GetOutputs() map[string]string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *Layer) GetImplicit() bool {
	if x != nil {
		return x.Implicit
	}
	return false
}

type AddLayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Layer         *LayerDefinition       `protobuf:"bytes,1,opt,name=layer,proto3" json:"layer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLayerRequest) Reset() {
	*x = AddLayerRequest{}
	mi := &file_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLayerRequest) ProtoMessage() {}

func (x *AddLayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLayerRequest.ProtoReflect.Descriptor instead.
func (*AddLayerRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{4}
}

func (x *AddLayerRequest) GetLayer() *LayerDefinition {
	if x != nil {
		return x.Layer
	}
	return nil
}

type GetLayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLayerRequest) Reset() {
	*x = GetLayerRequest{}
	mi := &file_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLayerRequest) ProtoMessage() {}

func (x *GetLayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLayerRequest.ProtoReflect.Descriptor instead.
func (*GetLayerRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{5}
}

func (x *GetLayerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Layer         *Layer                 `protobuf:"bytes,1,opt,name=layer,proto3" json:"layer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayerResponse) Reset() {
	*x = LayerResponse{}
	mi := &file_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerResponse) ProtoMessage() {}

func (x *LayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerResponse.ProtoReflect.Descriptor instead.
func (*LayerResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{6}
}

func (x *LayerResponse) GetLayer() *Layer {
	if x != nil {
		return x.Layer
	}
	return nil
}

type ListLayersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Layers        []*Layer               `protobuf:"bytes,1,rep,name=layers,proto3" json:"layers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLayersResponse) Reset() {
	*x = ListLayersResponse{}
	mi := &file_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLayersResponse) ProtoMessage() {}

func (x *ListLayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLayersResponse.ProtoReflect.Descriptor instead.
func (*ListLayersResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{7}
}

func (x *ListLayersResponse) GetLayers() []*Layer {
	if x != nil {
		return x.Layers
	}
	return nil
}

type RemoveLayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mode          RemoveLayerMode        `protobuf:"varint,2,opt,name=mode,proto3,enum=azdext.RemoveLayerMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveLayerRequest) Reset() {
	*x = RemoveLayerRequest{}
	mi := &file_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveLayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveLayerRequest) ProtoMessage() {}

func (x *RemoveLayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveLayerRequest.ProtoReflect.Descriptor instead.
func (*RemoveLayerRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveLayerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RemoveLayerRequest) GetMode() RemoveLayerMode {
	if x != nil {
		return x.Mode
	}
	return RemoveLayerMode_REMOVE_LAYER_MODE_REQUIRE_EMPTY
}

type RemoveLayerResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RemovedServices []string               `protobuf:"bytes,1,rep,name=removed_services,json=removedServices,proto3" json:"removed_services,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RemoveLayerResponse) Reset() {
	*x = RemoveLayerResponse{}
	mi := &file_project_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveLayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveLayerResponse) ProtoMessage() {}

func (x *RemoveLayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveLayerResponse.ProtoReflect.Descriptor instead.
func (*RemoveLayerResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveLayerResponse) GetRemovedServices() []string {
	if x != nil {
		return x.RemovedServices
	}
	return nil
}

type GetServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Layer         *string                `protobuf:"bytes,2,opt,name=layer,proto3,oneof" json:"layer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceRequest) Reset() {
	*x = GetServiceRequest{}
	mi := &file_project_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceRequest) ProtoMessage() {}

func (x *GetServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceRequest.ProtoReflect.Descriptor instead.
func (*GetServiceRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{10}
}

func (x *GetServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetServiceRequest) GetLayer() string {
	if x != nil && x.Layer != nil {
		return *x.Layer
	}
	return ""
}

type GetServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *ServiceConfig         `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceResponse) Reset() {
	*x = GetServiceResponse{}
	mi := &file_project_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceResponse) ProtoMessage() {}

func (x *GetServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceResponse.ProtoReflect.Descriptor instead.
func (*GetServiceResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{11}
}

func (x *GetServiceResponse) GetService() *ServiceConfig {
	if x != nil {
		return x.Service
	}
	return nil
}

// GetResolvedServicesResponse message definition
type GetResolvedServicesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of service name to service configuration
	Services      map[string]*ServiceConfig `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResolvedServicesResponse) Reset() {
	*x = GetResolvedServicesResponse{}
	mi := &file_project_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResolvedServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResolvedServicesResponse) ProtoMessage() {}

func (x *GetResolvedServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResolvedServicesResponse.ProtoReflect.Descriptor instead.
func (*GetResolvedServicesResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{12}
}

func (x *GetResolvedServicesResponse) GetServices() map[string]*ServiceConfig {
	if x != nil {
		return x.Services
	}
	return nil
}

// ParseGitHubUrlRequest message definition
type ParseGitHubUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseGitHubUrlRequest) Reset() {
	*x = ParseGitHubUrlRequest{}
	mi := &file_project_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseGitHubUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseGitHubUrlRequest) ProtoMessage() {}

func (x *ParseGitHubUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseGitHubUrlRequest.ProtoReflect.Descriptor instead.
func (*ParseGitHubUrlRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{13}
}

func (x *ParseGitHubUrlRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Request message for GetConfigSection
type GetProjectConfigSectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectConfigSectionRequest) Reset() {
	*x = GetProjectConfigSectionRequest{}
	mi := &file_project_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectConfigSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectConfigSectionRequest) ProtoMessage() {}

func (x *GetProjectConfigSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectConfigSectionRequest.ProtoReflect.Descriptor instead.
func (*GetProjectConfigSectionRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{14}
}

func (x *GetProjectConfigSectionRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Response message for GetConfigSection
type GetProjectConfigSectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Section       *structpb.Struct       `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectConfigSectionResponse) Reset() {
	*x = GetProjectConfigSectionResponse{}
	mi := &file_project_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectConfigSectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectConfigSectionResponse) ProtoMessage() {}

func (x *GetProjectConfigSectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectConfigSectionResponse.ProtoReflect.Descriptor instead.
func (*GetProjectConfigSectionResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{15}
}

func (x *GetProjectConfigSectionResponse) GetSection() *structpb.Struct {
	if x != nil {
		return x.Section
	}
	return nil
}

func (x *GetProjectConfigSectionResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// ParseGitHubUrlResponse message definition
type ParseGitHubUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	RepoSlug      string                 `protobuf:"bytes,2,opt,name=repo_slug,json=repoSlug,proto3" json:"repo_slug,omitempty"`
	Branch        string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	FilePath      string                 `protobuf:"bytes,4,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseGitHubUrlResponse) Reset() {
	*x = ParseGitHubUrlResponse{}
	mi := &file_project_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseGitHubUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseGitHubUrlResponse) ProtoMessage() {}

func (x *ParseGitHubUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseGitHubUrlResponse.ProtoReflect.Descriptor instead.
func (*ParseGitHubUrlResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{16}
}

func (x *ParseGitHubUrlResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ParseGitHubUrlResponse) GetRepoSlug() string {
	if x != nil {
		return x.RepoSlug
	}
	return ""
}

func (x *ParseGitHubUrlResponse) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *ParseGitHubUrlResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

// Request message for GetConfigValue
type GetProjectConfigValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectConfigValueRequest) Reset() {
	*x = GetProjectConfigValueRequest{}
	mi := &file_project_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectConfigValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectConfigValueRequest) ProtoMessage() {}

func (x *GetProjectConfigValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectConfigValueRequest.ProtoReflect.Descriptor instead.
func (*GetProjectConfigValueRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{17}
}

func (x *GetProjectConfigValueRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Response message for GetConfigValue
type GetProjectConfigValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *structpb.Value        `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectConfigValueResponse) Reset() {
	*x = GetProjectConfigValueResponse{}
	mi := &file_project_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectConfigValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectConfigValueResponse) ProtoMessage() {}

func (x *GetProjectConfigValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectConfigValueResponse.ProtoReflect.Descriptor instead.
func (*GetProjectConfigValueResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{18}
}

func (x *GetProjectConfigValueResponse) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetProjectConfigValueResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// Request message for SetConfigSection
type SetProjectConfigSectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Section       *structpb.Struct       `protobuf:"bytes,2,opt,name=section,proto3" json:"section,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProjectConfigSectionRequest) Reset() {
	*x = SetProjectConfigSectionRequest{}
	mi := &file_project_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProjectConfigSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProjectConfigSectionRequest) ProtoMessage() {}

func (x *SetProjectConfigSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProjectConfigSectionRequest.ProtoReflect.Descriptor instead.
func (*SetProjectConfigSectionRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{19}
}

func (x *SetProjectConfigSectionRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SetProjectConfigSectionRequest) GetSection() *structpb.Struct {
	if x != nil {
		return x.Section
	}
	return nil
}

// Request message for SetConfigValue
type SetProjectConfigValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProjectConfigValueRequest) Reset() {
	*x = SetProjectConfigValueRequest{}
	mi := &file_project_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProjectConfigValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProjectConfigValueRequest) ProtoMessage() {}

func (x *SetProjectConfigValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProjectConfigValueRequest.ProtoReflect.Descriptor instead.
func (*SetProjectConfigValueRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{20}
}

func (x *SetProjectConfigValueRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SetProjectConfigValueRequest) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// Request message for UnsetConfig
type UnsetProjectConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsetProjectConfigRequest) Reset() {
	*x = UnsetProjectConfigRequest{}
	mi := &file_project_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsetProjectConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsetProjectConfigRequest) ProtoMessage() {}

func (x *UnsetProjectConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsetProjectConfigRequest.ProtoReflect.Descriptor instead.
func (*UnsetProjectConfigRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{21}
}

func (x *UnsetProjectConfigRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Request message for GetServiceConfigSection
type GetServiceConfigSectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceConfigSectionRequest) Reset() {
	*x = GetServiceConfigSectionRequest{}
	mi := &file_project_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceConfigSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceConfigSectionRequest) ProtoMessage() {}

func (x *GetServiceConfigSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceConfigSectionRequest.ProtoReflect.Descriptor instead.
func (*GetServiceConfigSectionRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{22}
}

func (x *GetServiceConfigSectionRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetServiceConfigSectionRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Response message for GetServiceConfigSection
type GetServiceConfigSectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Section       *structpb.Struct       `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceConfigSectionResponse) Reset() {
	*x = GetServiceConfigSectionResponse{}
	mi := &file_project_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceConfigSectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceConfigSectionResponse) ProtoMessage() {}

func (x *GetServiceConfigSectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceConfigSectionResponse.ProtoReflect.Descriptor instead.
func (*GetServiceConfigSectionResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{23}
}

func (x *GetServiceConfigSectionResponse) GetSection() *structpb.Struct {
	if x != nil {
		return x.Section
	}
	return nil
}

func (x *GetServiceConfigSectionResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// Request message for GetServiceConfigValue
type GetServiceConfigValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceConfigValueRequest) Reset() {
	*x = GetServiceConfigValueRequest{}
	mi := &file_project_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceConfigValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceConfigValueRequest) ProtoMessage() {}

func (x *GetServiceConfigValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceConfigValueRequest.ProtoReflect.Descriptor instead.
func (*GetServiceConfigValueRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{24}
}

func (x *GetServiceConfigValueRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetServiceConfigValueRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Response message for GetServiceConfigValue
type GetServiceConfigValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *structpb.Value        `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceConfigValueResponse) Reset() {
	*x = GetServiceConfigValueResponse{}
	mi := &file_project_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceConfigValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceConfigValueResponse) ProtoMessage() {}

func (x *GetServiceConfigValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceConfigValueResponse.ProtoReflect.Descriptor instead.
func (*GetServiceConfigValueResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{25}
}

func (x *GetServiceConfigValueResponse) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetServiceConfigValueResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// Request message for SetServiceConfigSection
type SetServiceConfigSectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Section       *structpb.Struct       `protobuf:"bytes,3,opt,name=section,proto3" json:"section,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetServiceConfigSectionRequest) Reset() {
	*x = SetServiceConfigSectionRequest{}
	mi := &file_project_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetServiceConfigSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetServiceConfigSectionRequest) ProtoMessage() {}

func (x *SetServiceConfigSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetServiceConfigSectionRequest.ProtoReflect.Descriptor instead.
func (*SetServiceConfigSectionRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{26}
}

func (x *SetServiceConfigSectionRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SetServiceConfigSectionRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SetServiceConfigSectionRequest) GetSection() *structpb.Struct {
	if x != nil {
		return x.Section
	}
	return nil
}

// Request message for SetServiceConfigValue
type SetServiceConfigValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetServiceConfigValueRequest) Reset() {
	*x = SetServiceConfigValueRequest{}
	mi := &file_project_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetServiceConfigValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetServiceConfigValueRequest) ProtoMessage() {}

func (x *SetServiceConfigValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetServiceConfigValueRequest.ProtoReflect.Descriptor instead.
func (*SetServiceConfigValueRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{27}
}

func (x *SetServiceConfigValueRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SetServiceConfigValueRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SetServiceConfigValueRequest) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// Request message for UnsetServiceConfig
type UnsetServiceConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsetServiceConfigRequest) Reset() {
	*x = UnsetServiceConfigRequest{}
	mi := &file_project_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsetServiceConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsetServiceConfigRequest) ProtoMessage() {}

func (x *UnsetServiceConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsetServiceConfigRequest.ProtoReflect.Descriptor instead.
func (*UnsetServiceConfigRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{28}
}

func (x *UnsetServiceConfigRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *UnsetServiceConfigRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Request message for GetServiceTargetResource
type GetServiceTargetResourceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the service to resolve the target resource for
	ServiceName   string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceTargetResourceRequest) Reset() {
	*x = GetServiceTargetResourceRequest{}
	mi := &file_project_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceTargetResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceTargetResourceRequest) ProtoMessage() {}

func (x *GetServiceTargetResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceTargetResourceRequest.ProtoReflect.Descriptor instead.
func (*GetServiceTargetResourceRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{29}
}

func (x *GetServiceTargetResourceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

// Response message for GetServiceTargetResource
type GetServiceTargetResourceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resolved target resource including subscription, resource group, resource name, and resource type
	TargetResource *TargetResource `protobuf:"bytes,1,opt,name=target_resource,json=targetResource,proto3" json:"target_resource,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetServiceTargetResourceResponse) Reset() {
	*x = GetServiceTargetResourceResponse{}
	mi := &file_project_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceTargetResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceTargetResourceResponse) ProtoMessage() {}

func (x *GetServiceTargetResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceTargetResourceResponse.ProtoReflect.Descriptor instead.
func (*GetServiceTargetResourceResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{30}
}

func (x *GetServiceTargetResourceResponse) GetTargetResource() *TargetResource {
	if x != nil {
		return x.TargetResource
	}
	return nil
}

var File_project_proto protoreflect.FileDescriptor

const file_project_proto_rawDesc = "" +
	"\n" +
	"\rproject.proto\x12\x06azdext\x1a\fmodels.proto\x1a\x14service_target.proto\x1a$include/google/protobuf/struct.proto\"E\n" +
	"\x12GetProjectResponse\x12/\n" +
	"\aproject\x18\x01 \x01(\v2\x15.azdext.ProjectConfigR\aproject\"D\n" +
	"\x11AddServiceRequest\x12/\n" +
	"\aservice\x18\x01 \x01(\v2\x15.azdext.ServiceConfigR\aservice\"\xe4\x02\n" +
	"\x0fLayerDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x05infra\x18\x02 \x01(\v2\x14.azdext.InfraOptionsR\x05infra\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x03 \x03(\tR\tdependsOn\x12;\n" +
	"\x06inputs\x18\x04 \x03(\v2#.azdext.LayerDefinition.InputsEntryR\x06inputs\x12>\n" +
	"\aoutputs\x18\x05 \x03(\v2$.azdext.LayerDefinition.OutputsEntryR\aoutputs\x1a9\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xef\x03\n" +
	"\x05Layer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x05infra\x18\x02 \x01(\v2\x14.azdext.InfraOptionsR\x05infra\x127\n" +
	"\bservices\x18\x03 \x03(\v2\x1b.azdext.Layer.ServicesEntryR\bservices\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x04 \x03(\tR\tdependsOn\x121\n" +
	"\x06inputs\x18\x05 \x03(\v2\x19.azdext.Layer.InputsEntryR\x06inputs\x124\n" +
	"\aoutputs\x18\x06 \x03(\v2\x1a.azdext.Layer.OutputsEntryR\aoutputs\x12\x1a\n" +
	"\bimplicit\x18\a \x01(\bR\bimplicit\x1aR\n" +
	"\rServicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.azdext.ServiceConfigR\x05value:\x028\x01\x1a9\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\x0fAddLayerRequest\x12-\n" +
	"\x05layer\x18\x01 \x01(\v2\x17.azdext.LayerDefinitionR\x05layer\"%\n" +
	"\x0fGetLayerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"4\n" +
	"\rLayerResponse\x12#\n" +
	"\x05layer\x18\x01 \x01(\v2\r.azdext.LayerR\x05layer\";\n" +
	"\x12ListLayersResponse\x12%\n" +
	"\x06layers\x18\x01 \x03(\v2\r.azdext.LayerR\x06layers\"U\n" +
	"\x12RemoveLayerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x17.azdext.RemoveLayerModeR\x04mode\"@\n" +
	"\x13RemoveLayerResponse\x12)\n" +
	"\x10removed_services\x18\x01 \x03(\tR\x0fremovedServices\"[\n" +
	"\x11GetServiceRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x19\n" +
	"\x05layer\x18\x02 \x01(\tH\x00R\x05layer\x88\x01\x01B\b\n" +
	"\x06_layer\"E\n" +
	"\x12GetServiceResponse\x12/\n" +
	"\aservice\x18\x01 \x01(\v2\x15.azdext.ServiceConfigR\aservice\"\xc0\x01\n" +
	"\x1bGetResolvedServicesResponse\x12M\n" +
	"\bservices\x18\x01 \x03(\v21.azdext.GetResolvedServicesResponse.ServicesEntryR\bservices\x1aR\n" +
	"\rServicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.azdext.ServiceConfigR\x05value:\x028\x01\")\n" +
	"\x15ParseGitHubUrlRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"4\n" +
	"\x1eGetProjectConfigSectionRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"j\n" +
	"\x1fGetProjectConfigSectionResponse\x121\n" +
	"\asection\x18\x01 \x01(\v2\x17.google.protobuf.StructR\asection\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\x86\x01\n" +
	"\x16ParseGitHubUrlResponse\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1b\n" +
	"\trepo_slug\x18\x02 \x01(\tR\brepoSlug\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\x12\x1b\n" +
	"\tfile_path\x18\x04 \x01(\tR\bfilePath\"2\n" +
	"\x1cGetProjectConfigValueRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"c\n" +
	"\x1dGetProjectConfigValueResponse\x12,\n" +
	"\x05value\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"g\n" +
	"\x1eSetProjectConfigSectionRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x121\n" +
	"\asection\x18\x02 \x01(\v2\x17.google.protobuf.StructR\asection\"`\n" +
	"\x1cSetProjectConfigValueRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value\"/\n" +
	"\x19UnsetProjectConfigRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"W\n" +
	"\x1eGetServiceConfigSectionRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"j\n" +
	"\x1fGetServiceConfigSectionResponse\x121\n" +
	"\asection\x18\x01 \x01(\v2\x17.google.protobuf.StructR\asection\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"U\n" +
	"\x1cGetServiceConfigValueRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"c\n" +
	"\x1dGetServiceConfigValueResponse\x12,\n" +
	"\x05value\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\x8a\x01\n" +
	"\x1eSetServiceConfigSectionRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x121\n" +
	"\asection\x18\x03 \x01(\v2\x17.google.protobuf.StructR\asection\"\x83\x01\n" +
	"\x1cSetServiceConfigValueRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12,\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x05value\"R\n" +
	"\x19UnsetServiceConfigRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"D\n" +
	"\x1fGetServiceTargetResourceRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"c\n" +
	" GetServiceTargetResourceResponse\x12?\n" +
	"\x0ftarget_resource\x18\x01 \x01(\v2\x16.azdext.TargetResourceR\x0etargetResource*^\n" +
	"\x0fRemoveLayerMode\x12#\n" +
	"\x1fREMOVE_LAYER_MODE_REQUIRE_EMPTY\x10\x00\x12&\n" +
	"\"REMOVE_LAYER_MODE_CASCADE_SERVICES\x10\x012\xe1\f\n" +
	"\x0eProjectService\x127\n" +
	"\x03Get\x12\x14.azdext.EmptyRequest\x1a\x1a.azdext.GetProjectResponse\x12m\n" +
	"\x18GetServiceTargetResource\x12'.azdext.GetServiceTargetResourceRequest\x1a(.azdext.GetServiceTargetResourceResponse\x12>\n" +
	"\n" +
	"AddService\x12\x19.azdext.AddServiceRequest\x1a\x15.azdext.EmptyResponse\x12:\n" +
	"\bAddLayer\x12\x17.azdext.AddLayerRequest\x1a\x15.azdext.LayerResponse\x12:\n" +
	"\bGetLayer\x12\x17.azdext.GetLayerRequest\x1a\x15.azdext.LayerResponse\x12>\n" +
	"\n" +
	"ListLayers\x12\x14.azdext.EmptyRequest\x1a\x1a.azdext.ListLayersResponse\x12F\n" +
	"\vRemoveLayer\x12\x1a.azdext.RemoveLayerRequest\x1a\x1b.azdext.RemoveLayerResponse\x12C\n" +
	"\n" +
	"GetService\x12\x19.azdext.GetServiceRequest\x1a\x1a.azdext.GetServiceResponse\x12P\n" +
	"\x13GetResolvedServices\x12\x14.azdext.EmptyRequest\x1a#.azdext.GetResolvedServicesResponse\x12O\n" +
	"\x0eParseGitHubUrl\x12\x1d.azdext.ParseGitHubUrlRequest\x1a\x1e.azdext.ParseGitHubUrlResponse\x12c\n" +
	"\x10GetConfigSection\x12&.azdext.GetProjectConfigSectionRequest\x1a'.azdext.GetProjectConfigSectionResponse\x12]\n" +
	"\x0eGetConfigValue\x12$.azdext.GetProjectConfigValueRequest\x1a%.azdext.GetProjectConfigValueResponse\x12Q\n" +
	"\x10SetConfigSection\x12&.azdext.SetProjectConfigSectionRequest\x1a\x15.azdext.EmptyResponse\x12M\n" +
	"\x0eSetConfigValue\x12$.azdext.SetProjectConfigValueRequest\x1a\x15.azdext.EmptyResponse\x12G\n" +
	"\vUnsetConfig\x12!.azdext.UnsetProjectConfigRequest\x1a\x15.azdext.EmptyResponse\x12j\n" +
	"\x17GetServiceConfigSection\x12&.azdext.GetServiceConfigSectionRequest\x1a'.azdext.GetServiceConfigSectionResponse\x12d\n" +
	"\x15GetServiceConfigValue\x12$.azdext.GetServiceConfigValueRequest\x1a%.azdext.GetServiceConfigValueResponse\x12X\n" +
	"\x17SetServiceConfigSection\x12&.azdext.SetServiceConfigSectionRequest\x1a\x15.azdext.EmptyResponse\x12T\n" +
	"\x15SetServiceConfigValue\x12$.azdext.SetServiceConfigValueRequest\x1a\x15.azdext.EmptyResponse\x12N\n" +
	"\x12UnsetServiceConfig\x12!.azdext.UnsetServiceConfigRequest\x1a\x15.azdext.EmptyResponseB/Z-github.com/azure/azure-dev/cli/azd/pkg/azdextb\x06proto3"

var (
	file_project_proto_rawDescOnce sync.Once
	file_project_proto_rawDescData []byte
)

func file_project_proto_rawDescGZIP() []byte {
	file_project_proto_rawDescOnce.Do(func() {
		file_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_project_proto_rawDesc), len(file_project_proto_rawDesc)))
	})
	return file_project_proto_rawDescData
}

var file_project_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_project_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_project_proto_goTypes = []any{
	(RemoveLayerMode)(0),                     // 0: azdext.RemoveLayerMode
	(*GetProjectResponse)(nil),               // 1: azdext.GetProjectResponse
	(*AddServiceRequest)(nil),                // 2: azdext.AddServiceRequest
	(*LayerDefinition)(nil),                  // 3: azdext.LayerDefinition
	(*Layer)(nil),                            // 4: azdext.Layer
	(*AddLayerRequest)(nil),                  // 5: azdext.AddLayerRequest
	(*GetLayerRequest)(nil),                  // 6: azdext.GetLayerRequest
	(*LayerResponse)(nil),                    // 7: azdext.LayerResponse
	(*ListLayersResponse)(nil),               // 8: azdext.ListLayersResponse
	(*RemoveLayerRequest)(nil),               // 9: azdext.RemoveLayerRequest
	(*RemoveLayerResponse)(nil),              // 10: azdext.RemoveLayerResponse
	(*GetServiceRequest)(nil),                // 11: azdext.GetServiceRequest
	(*GetServiceResponse)(nil),               // 12: azdext.GetServiceResponse
	(*GetResolvedServicesResponse)(nil),      // 13: azdext.GetResolvedServicesResponse
	(*ParseGitHubUrlRequest)(nil),            // 14: azdext.ParseGitHubUrlRequest
	(*GetProjectConfigSectionRequest)(nil),   // 15: azdext.GetProjectConfigSectionRequest
	(*GetProjectConfigSectionResponse)(nil),  // 16: azdext.GetProjectConfigSectionResponse
	(*ParseGitHubUrlResponse)(nil),           // 17: azdext.ParseGitHubUrlResponse
	(*GetProjectConfigValueRequest)(nil),     // 18: azdext.GetProjectConfigValueRequest
	(*GetProjectConfigValueResponse)(nil),    // 19: azdext.GetProjectConfigValueResponse
	(*SetProjectConfigSectionRequest)(nil),   // 20: azdext.SetProjectConfigSectionRequest
	(*SetProjectConfigValueRequest)(nil),     // 21: azdext.SetProjectConfigValueRequest
	(*UnsetProjectConfigRequest)(nil),        // 22: azdext.UnsetProjectConfigRequest
	(*GetServiceConfigSectionRequest)(nil),   // 23: azdext.GetServiceConfigSectionRequest
	(*GetServiceConfigSectionResponse)(nil),  // 24: azdext.GetServiceConfigSectionResponse
	(*GetServiceConfigValueRequest)(nil),     // 25: azdext.GetServiceConfigValueRequest
	(*GetServiceConfigValueResponse)(nil),    // 26: azdext.GetServiceConfigValueResponse
	(*SetServiceConfigSectionRequest)(nil),   // 27: azdext.SetServiceConfigSectionRequest
	(*SetServiceConfigValueRequest)(nil),     // 28: azdext.SetServiceConfigValueRequest
	(*UnsetServiceConfigRequest)(nil),        // 29: azdext.UnsetServiceConfigRequest
	(*GetServiceTargetResourceRequest)(nil),  // 30: azdext.GetServiceTargetResourceRequest
	(*GetServiceTargetResourceResponse)(nil), // 31: azdext.GetServiceTargetResourceResponse
	nil,                                      // 32: azdext.LayerDefinition.InputsEntry
	nil,                                      // 33: azdext.LayerDefinition.OutputsEntry
	nil,                                      // 34: azdext.Layer.ServicesEntry
	nil,                                      // 35: azdext.Layer.InputsEntry
	nil,                                      // 36: azdext.Layer.OutputsEntry
	nil,                                      // 37: azdext.GetResolvedServicesResponse.ServicesEntry
	(*ProjectConfig)(nil),                    // 38: azdext.ProjectConfig
	(*ServiceConfig)(nil),                    // 39: azdext.ServiceConfig
	(*InfraOptions)(nil),                     // 40: azdext.InfraOptions
	(*structpb.Struct)(nil),                  // 41: google.protobuf.Struct
	(*structpb.Value)(nil),                   // 42: google.protobuf.Value
	(*TargetResource)(nil),                   // 43: azdext.TargetResource
	(*EmptyRequest)(nil),                     // 44: azdext.EmptyRequest
	(*EmptyResponse)(nil),                    // 45: azdext.EmptyResponse
}
var file_project_proto_depIdxs = []int32{
	38, // 0: azdext.GetProjectResponse.project:type_name -> azdext.ProjectConfig
	39, // 1: azdext.AddServiceRequest.service:type_name -> azdext.ServiceConfig
	40, // 2: azdext.LayerDefinition.infra:type_name -> azdext.InfraOptions
	32, // 3: azdext.LayerDefinition.inputs:type_name -> azdext.LayerDefinition.InputsEntry
	33, // 4: azdext.LayerDefinition.outputs:type_name -> azdext.LayerDefinition.OutputsEntry
	40, // 5: azdext.Layer.infra:type_name -> azdext.InfraOptions
	34, // 6: azdext.Layer.services:type_name -> azdext.Layer.ServicesEntry
	35, // 7: azdext.Layer.inputs:type_name -> azdext.Layer.InputsEntry
	36, // 8: azdext.Layer.outputs:type_name -> azdext.Layer.OutputsEntry
	3,  // 9: azdext.AddLayerRequest.layer:type_name -> azdext.LayerDefinition
	4,  // 10: azdext.LayerResponse.layer:type_name -> azdext.Layer
	4,  // 11: azdext.ListLayersResponse.layers:type_name -> azdext.Layer
	0,  // 12: azdext.RemoveLayerRequest.mode:type_name -> azdext.RemoveLayerMode
	39, // 13: azdext.GetServiceResponse.service:type_name -> azdext.ServiceConfig
	37, // 14: azdext.GetResolvedServicesResponse.services:type_name -> azdext.GetResolvedServicesResponse.ServicesEntry
	41, // 15: azdext.GetProjectConfigSectionResponse.section:type_name -> google.protobuf.Struct
	42, // 16: azdext.GetProjectConfigValueResponse.value:type_name -> google.protobuf.Value
	41, // 17: azdext.SetProjectConfigSectionRequest.section:type_name -> google.protobuf.Struct
	42, // 18: azdext.SetProjectConfigValueRequest.value:type_name -> google.protobuf.Value
	41, // 19: azdext.GetServiceConfigSectionResponse.section:type_name -> google.protobuf.Struct
	42, // 20: azdext.GetServiceConfigValueResponse.value:type_name -> google.protobuf.Value
	41, // 21: azdext.SetServiceConfigSectionRequest.section:type_name -> google.protobuf.Struct
	42, // 22: azdext.SetServiceConfigValueRequest.value:type_name -> google.protobuf.Value
	43, // 23: azdext.GetServiceTargetResourceResponse.target_resource:type_name -> azdext.TargetResource
	39, // 24: azdext.Layer.ServicesEntry.value:type_name -> azdext.ServiceConfig
	39, // 25: azdext.GetResolvedServicesResponse.ServicesEntry.value:type_name -> azdext.ServiceConfig
	44, // 26: azdext.ProjectService.Get:input_type -> azdext.EmptyRequest
	30, // 27: azdext.ProjectService.GetServiceTargetResource:input_type -> azdext.GetServiceTargetResourceRequest
	2,  // 28: azdext.ProjectService.AddService:input_type -> azdext.AddServiceRequest
	5,  // 29: azdext.ProjectService.AddLayer:input_type -> azdext.AddLayerRequest
	6,  // 30: azdext.ProjectService.GetLayer:input_type -> azdext.GetLayerRequest
	44, // 31: azdext.ProjectService.ListLayers:input_type -> azdext.EmptyRequest
	9,  // 32: azdext.ProjectService.RemoveLayer:input_type -> azdext.RemoveLayerRequest
	11, // 33: azdext.ProjectService.GetService:input_type -> azdext.GetServiceRequest
	44, // 34: azdext.ProjectService.GetResolvedServices:input_type -> azdext.EmptyRequest
	14, // 35: azdext.ProjectService.ParseGitHubUrl:input_type -> azdext.ParseGitHubUrlRequest
	15, // 36: azdext.ProjectService.GetConfigSection:input_type -> azdext.GetProjectConfigSectionRequest
	18, // 37: azdext.ProjectService.GetConfigValue:input_type -> azdext.GetProjectConfigValueRequest
	20, // 38: azdext.ProjectService.SetConfigSection:input_type -> azdext.SetProjectConfigSectionRequest
	21, // 39: azdext.ProjectService.SetConfigValue:input_type -> azdext.SetProjectConfigValueRequest
	22, // 40: azdext.ProjectService.UnsetConfig:input_type -> azdext.UnsetProjectConfigRequest
	23, // 41: azdext.ProjectService.GetServiceConfigSection:input_type -> azdext.GetServiceConfigSectionRequest
	25, // 42: azdext.ProjectService.GetServiceConfigValue:input_type -> azdext.GetServiceConfigValueRequest
	27, // 43: azdext.ProjectService.SetServiceConfigSection:input_type -> azdext.SetServiceConfigSectionRequest
	28, // 44: azdext.ProjectService.SetServiceConfigValue:input_type -> azdext.SetServiceConfigValueRequest
	29, // 45: azdext.ProjectService.UnsetServiceConfig:input_type -> azdext.UnsetServiceConfigRequest
	1,  // 46: azdext.ProjectService.Get:output_type -> azdext.GetProjectResponse
	31, // 47: azdext.ProjectService.GetServiceTargetResource:output_type -> azdext.GetServiceTargetResourceResponse
	45, // 48: azdext.ProjectService.AddService:output_type -> azdext.EmptyResponse
	7,  // 49: azdext.ProjectService.AddLayer:output_type -> azdext.LayerResponse
	7,  // 50: azdext.ProjectService.GetLayer:output_type -> azdext.LayerResponse
	8,  // 51: azdext.ProjectService.ListLayers:output_type -> azdext.ListLayersResponse
	10, // 52: azdext.ProjectService.RemoveLayer:output_type -> azdext.RemoveLayerResponse
	12, // 53: azdext.ProjectService.GetService:output_type -> azdext.GetServiceResponse
	13, // 54: azdext.ProjectService.GetResolvedServices:output_type -> azdext.GetResolvedServicesResponse
	17, // 55: azdext.ProjectService.ParseGitHubUrl:output_type -> azdext.ParseGitHubUrlResponse
	16, // 56: azdext.ProjectService.GetConfigSection:output_type -> azdext.GetProjectConfigSectionResponse
	19, // 57: azdext.ProjectService.GetConfigValue:output_type -> azdext.GetProjectConfigValueResponse
	45, // 58: azdext.ProjectService.SetConfigSection:output_type -> azdext.EmptyResponse
	45, // 59: azdext.ProjectService.SetConfigValue:output_type -> azdext.EmptyResponse
	45, // 60: azdext.ProjectService.UnsetConfig:output_type -> azdext.EmptyResponse
	24, // 61: azdext.ProjectService.GetServiceConfigSection:output_type -> azdext.GetServiceConfigSectionResponse
	26, // 62: azdext.ProjectService.GetServiceConfigValue:output_type -> azdext.GetServiceConfigValueResponse
	45, // 63: azdext.ProjectService.SetServiceConfigSection:output_type -> azdext.EmptyResponse
	45, // 64: azdext.ProjectService.SetServiceConfigValue:output_type -> azdext.EmptyResponse
	45, // 65: azdext.ProjectService.UnsetServiceConfig:output_type -> azdext.EmptyResponse
	46, // [46:66] is the sub-list for method output_type
	26, // [26:46] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_project_proto_init() }
func file_project_proto_init() {
	if File_project_proto != nil {
		return
	}
	file_models_proto_init()
	file_service_target_proto_init()
	file_project_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_project_proto_rawDesc), len(file_project_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_project_proto_goTypes,
		DependencyIndexes: file_project_proto_depIdxs,
		EnumInfos:         file_project_proto_enumTypes,
		MessageInfos:      file_project_proto_msgTypes,
	}.Build()
	File_project_proto = out.File
	file_project_proto_goTypes = nil
	file_project_proto_depIdxs = nil
}
